### ISSUE TITLE
Latest Wagtail does not have wagtail.core modul

### ISSUE THREAD

**Issue by Roland-Szucs** [cursive-works/wagtail-grafl#1]
The latest wagtail and maybe some previous ones have no wagtail.core module anymore. That's why line number 8 in wagtail_grafl/blocks.py fails.

**Comment by marts** [comment]
Hi @Roland-Szucs thank you for pointing this out. I've uploaded a new version to pypi. https://pypi.org/project/wagtail-grafl/
